name: apply-template
# Download and initialize a project template from siili-ai-sdk
#
# Usage:
#   siili-agent-workflows apply-template --template agent --path ./my-agent
#   siili-agent-workflows apply-template --template server --path ./my-server
#   siili-agent-workflows apply-template --template frontend --path ./my-frontend
#
# Available templates:
#   - agent: Python agent with BaseAgent
#   - server: FastAPI server with agent endpoints
#   - frontend: React frontend with chat UI

jobs:
  apply:
    steps:
      - uses: git/download
        with:
          repo: "https://github.com/siilisolutions/siili-ai-sdk.git"
          ref: "main"
          files:
            - "templates/${{ template }}"
          dest: "${{ path }}"

      - uses: terminal/script
        with:
          path: "${{ path }}/init_template.sh"
          cwd: "${{ path }}"
          continue_on_error: true
